# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.TextField(max_length=500),
        ),
    ]
