# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_auto_20160604_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
