# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_photo_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='tags', to='blogpost.Article'),
        ),
    ]
